# Generated by Django 3.0.4 on 2020-04-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaultPost.jpg', upload_to='post_pics'),
        ),
    ]
