# Generated by Django 3.0.4 on 2020-04-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200410_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dif',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Intermediate'), ('3', 'Advanced')], default=('2', 'Intermediate'), max_length=40),
        ),
    ]
