# Generated by Django 3.0.4 on 2020-04-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_dif'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.CharField(default='00:30', max_length=5),
        ),
    ]
