# Generated by Django 3.0.4 on 2020-04-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200410_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dif',
            new_name='difficulty',
        ),
    ]
