# Generated by Django 3.0.4 on 2020-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200410_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='servings',
            field=models.CharField(default='4', max_length=2),
        ),
    ]
