# Generated by Django 3.0.4 on 2020-05-13 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200513_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='date_liked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
